var width = 7;
var height = 4;
var area = width * height;
var bill = 10;
var payment = 4.5;
var change = bill - payment;
var quizzes = 100;
var midterm = 25;
var final = 25;
var grade = (quizzes + midterm + final) / 3;
var firstName = 'Jc';
var lastName = 'Leon';
var fullName = firstName + ' ' + lastName;
var pH = 5;
var isAcidic = pH < 7;
var headCount = 250;
var isSparta = headCount === 300;
var motto = fullName + ' is the GOAT';

console.log('value of area:', area);
console.log('typeof of area:', typeof area);
console.log('value of change:', change);
console.log('typeof of change:', typeof change);
console.log('value of grade:', grade);
console.log('typeof of grade:', typeof grade);
console.log('value of fullName:', fullName);
console.log('typeof of fullName:', typeof fullName);
console.log('value of isAcidic:', isAcidic);
console.log('typeof of isAcidic:', typeof isAcidic);
console.log('value of isSparta:', isSparta);
console.log('typeof of isSparta:', typeof isSparta);
console.log('value of motto:', motto);
console.log('typeof of motto:', typeof motto);
